when:
  - event:
      - push
      - pull_request

steps:
  - name: test
    image: nixos/nix:2.31.0
    commands:
      - nix --extra-experimental-features "nix-command flakes" build --print-build-logs --no-link .#clippy .#test
  - name: build
    image: nixos/nix:2.31.0
    commands:
      - nix --extra-experimental-features "nix-command flakes" build --print-build-logs --no-link .#dockerImage
