on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v6
    - uses: DeterminateSystems/nix-installer-action@v13
    - uses: DeterminateSystems/magic-nix-cache-action@v13
      with:
        use-flakehub: false
    - name: Build default package
      run: nix build .
  devshell:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v6
    - uses: DeterminateSystems/nix-installer-action@v13
    - uses: DeterminateSystems/magic-nix-cache-action@v13
      with:
        use-flakehub: false
    - name: Build default dev shell
      run: nix build .#devShells.x86_64-linux.default
